### ISSUE TITLE
Issue authenticating from Standard Notes container to Standardfile container

### ISSUE THREAD

**Issue by maxengel** [Dryusdan/docker-standardfile#1]
I have everything setup via nginx-proxy so I have https://notes.domain.com and https://notesdb.domain.com. Everything seems to be working correctly, but when I try to create an account with the Standardfile URL (https://notesdb.domain.com) Standard Notes' web app returns:

`A server error occurred while trying to register. Please try again.`

When I check the Docker logs for standardfile, it shows:
```
Mysql2::Error (Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory")):
  
app/controllers/api/auth_controller.rb:23:in `register'
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (4.3ms)
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.5ms)
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (28.7ms)
Started POST "/auth" for 73.114.179.168 at 2018-01-27 23:58:29 +0000
Processing by Api::AuthController#register as */*
  Parameters: {"password"=>"[FILTERED]", "email"=>"name@domain.com", "pw_salt"=>"1ade790b8167b3f6d55bd96b852c109ea558e6cdba1957fd7691e00d1a69f6e5", "pw_cost"=>101000, "version"=>"002", "a
uth"=>{"password"=>"[FILTERED]", "email"=>"name@domain.com", "pw_salt"=>"1ade790b8167b3f6d55bd96b852c109ea558e6cdba1957fd7691e00d1a69f6e5", "pw_cost"=>101000, "version"=>"002"}}
Can't verify CSRF token authenticity.
Completed 500 Internal Server Error in 1ms
  
Mysql2::Error (Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory")):
  
app/controllers/api/auth_controller.rb:23:in `register'
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (4.6ms)
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.3ms)
  Rendering /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.6ms)
  Rendered /usr/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (30.1ms)`
```

**Comment by Dryusdan** [comment]
Ho... Sorry, I don't document this container 😶 

In your docker-compose file, add `env_file: /home/docker/services/standardfiles/.env.app.production `

And in your env.app.production : add 

```
RAILS_ENV=production
SECRET_KEY_BASE=use "bundle exec rake secret"
RAILS_SERVE_STATIC_FILES=true

DB_HOST=ipofdb
DB_PORT=3306
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

SALT_PSEUDO_NONCE=bitcharsalt

```

:)

**Comment by maxengel** [comment]
Thanks so much! I'm working on building a self-host StandardNotes instance running your two containers with nginx-proxy and the lets encrypt companion container.

Would the IP be internal inside the network, or the external IP?

**Comment by Dryusdan** [comment]
IP of DB ? If you use a link, you can remplace this by db. Else, it's IP of internal container or BDD on dedicate vps (for exemple)

**Comment by maxengel** [comment]
Sorry, to clarify, since I'm running all of these containers on a single VM, in your sample env you have:
`DB_HOST=ipofdb` and I am trying to determine the right IP to put there.

**Comment by Dryusdan** [comment]
Ho, okay.
If you DB is on VM (not on container), put here IP of VM
If is on container, two options : 
put ip of container here if you have fix ip (with network option), else if you use link method, put link name of db

**Comment by maxengel** [comment]
So would you recommend creating a MariaDB container as well?

**Comment by Dryusdan** [comment]
Yes, I recommand creating a MariaDB container and link them with standardfile container

**Comment by maxengel** [comment]
Got it, thanks. I'll on setting that up. If I get all parts working, I'll contribute my documentation.

**Comment by Dryusdan** [comment]
Thank you :)

**Comment by alexkutsan** [comment]
@maxengel  have you succeed with using standard notes app behind lets encrypt companion container (nginx-letsencrypt) ? I am doing the same now and have similar issues (`A server error occurred while trying to register. Please try again.`) 

As I know there are 3 parts of SN: 
 - web app 
 - sync server 
 - database 

For now I tried to use https://github.com/arugifa/standardnotes-server-docker( it looks extremely light weight and easy to deploy) for **sync server and database**.  With adding appropriate variables to `.env file` : VIRTUAL_{PORT,HOST}. LETSENCRYPT_HOST, email, etc ... 

 I suppose that issue is that nginx-letsencrypt exposes to internet port 80, and proxies it to port 3000 in the container, so port 3000 in unaccessible from web.  

@Dryusdan  Sorry for the offtopic probably.
